### ISSUE TITLE
Batch downloading a complete profile

### ISSUE THREAD

**Issue by waswosi** [EltonChou/TwitterMediaHarvest#100]
Since furyutei's twitter downloader has gone and batch download doesn't work anymore, how can you batch download a profile with the harvester here. Sorry I didn't find such a function.

**Comment by EltonChou** [comment]
This extension won't provide batch download feature.
You should use other tools like [gallery-dl](https://github.com/mikf/gallery-dl).

**Comment by EltonChou** [comment]
You need to read [the announcement](https://memo.furyutei.com/entry/20230831/1693485250) in Furyutei's blog.
I have same concern about X's policy.

The most of features you said are related to web crawler and this extension is not a web crawler.
You need adequate knowledge when you manipulate a crawler or you will get in the trouble.
If I want to do those things, I have my own tool-chain and strategies, but it won't be a web-extension.
