### ISSUE TITLE
[BUG] Twitter UI change causes button to be out of place

### ISSUE THREAD

**Issue by fireattack** [EltonChou/TwitterMediaHarvest#101]
**Describe the bug**
Probably already known, but I guess it does  no harm to make an issue.

Due to recent Twitter change, the button now is squeezed together with the last one:

**Screenshots**

![image](https://github.com/EltonChou/TwitterMediaHarvest/assets/4130991/fbbf61a1-81c2-44fa-97cc-724c58733154)

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser Chrome 
 - Version 117.0.5938.92 (Official Build) (64-bit) (cohort: Stable)

**Comment by EltonChou** [comment]
Should be fixed in v4.2.1. 
Feel free to reopen if the issue happend again.

**Comment by fireattack** [comment]
![image](https://github.com/EltonChou/TwitterMediaHarvest/assets/4130991/385b88ed-7dc4-4f71-9920-9056011f2168)


It looks Twitter broke it again

**Comment by EltonChou** [comment]
Inconsistent in some tweets, would be fixed in next patch.
Also, feel free to reopen this anytime.
