### ISSUE TITLE
Bulk Download in ZIP file

### ISSUE THREAD

**Issue by qtjohn** [EltonChou/TwitterMediaHarvest#104]
**Describe the solution you'd like**
The ability to download a ZIP file with all the posts from that page.

**Describe alternatives you've considered**
https://memo.furyutei.com/entry/20160723/1469282864#f-0b437fc7
https://cdn-ak.f.st-hatena.com/images/fotolife/f/furyu-tei/20171029/20171029090641.png

**Additional context**
When downloading the photos as ZIP files, an advantage is that the file creation date remains the date of the actual post.

**Comment by EltonChou** [comment]
This extension won't provide batch download feature.
You should use other tools like [gallery-dl](https://github.com/mikf/gallery-dl).

If you want the filename named with post datetime check your filename pattern setting in options page.
