### ISSUE TITLE
[BUG] downloaded are inserted with the wrong name and wrong format outside the related folder.

### ISSUE THREAD

**Issue by fscrow** [EltonChou/TwitterMediaHarvest#106]
**Describe the bug**
Hello, I have been using your extension for two years but I have encountered a problem for a few months. When I click on the download button, the files that are downloaded are inserted with the wrong name and wrong format outside the related folder.

**Screenshots**
![3cyayLe2rj]**Screenshots**(https://github.com/EltonChou/TwitterMediaHarvest/assets/54007599/8d708bf0-2c00-4532-b4c5-d1790d2aac5f)

 - OS: windows11
 - Browser [ chrome]

**Comment by EltonChou** [comment]
I think you have installed more than one download mangement extensions.
This will cause race condition, it a know  issue in chromium bases browser.

You can try to enable `Aggressive Mode` (options > integrations ), it might fix this problem.

**Comment by EltonChou** [comment]
No further response.
