### ISSUE TITLE
[BUG] 

### ISSUE THREAD

**Issue by pighair** [EltonChou/TwitterMediaHarvest#108]
**Describe the bug**
Batch download from Media tab is not working

**To Reproduce**
1. Go to a user's Media tab
2. Click on "Media" download link
3. Input start date
4. Click on "Start" with Images, Videos(GIF), Videos checked
5. See the error

**Expected behavior**
Start download all medias of the user within period

**Screenshots**
![image](https://github.com/EltonChou/TwitterMediaHarvest/assets/18534209/03d9f45c-73e3-4a6b-b30d-a869534187f3)

**Desktop (please complete the following information):**
 - OS: macOS 14.0
 - Browser: chrome
 - Version 117.0.5938.149

**Additional context**
Same error happens with Windows Chrome.

**Comment by EltonChou** [comment]
Wrong place, I didn't implement this feature.
