### ISSUE TITLE
[BUG] The file is always downloaded with a random name and not according to Account ID, for example

### ISSUE THREAD

**Issue by TareqAbAmawi** [EltonChou/TwitterMediaHarvest#109]
**Describe the bug**
The file is always downloaded with a random name and not according to Account ID, for example

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [WIN11]
 - Browser [chrome,]
 - Version [Last]

**Additional context**
The problem appeared about a week ago

**Comment by EltonChou** [comment]
Please ensure you only enable one download management extension or there would be some race conditions.
This is a known issue on chromium based browser.
