### ISSUE TITLE
[BUG] found an account and the download button disappeared under its tweets.

### ISSUE THREAD

**Issue by cyanlamp247** [EltonChou/TwitterMediaHarvest#113]
@thinkerstatus

maybe it’s because username contains ‘status’

**Comment by EltonChou** [comment]
Yes, you are right.
This issue was caused by https://github.com/EltonChou/TwitterMediaHarvest/blob/752779daad4cee02e1d44fd56aab1054c8cc6051/src/content_script/utils/article.ts#L61
