### ISSUE TITLE
[BUG] "Forbidden - Your login session might be expired, please refresh your page"

### ISSUE THREAD

**Issue by borez** [EltonChou/TwitterMediaHarvest#115]
**Describe the bug**
I get the following error when trying to download from twitter. Clicking on the view button below brings me to the actual post but still no dice.

Get this same error across all browsers.
EDIT: realised that this happens when I am in Incongito mode. Running it on a main browser works.

**To Reproduce**
Clicking on the download button.

**Expected behavior**

**Screenshots**
<img width="274" alt="image" src="https://github.com/EltonChou/TwitterMediaHarvest/assets/26034141/33a3097e-edfb-4a11-9cae-834910f09b11">
**Desktop (please complete the following information):**
Windows 11 
Chrome
Extension version at 4.2.2

**Additional context**

**Comment by EltonChou** [comment]
Can't reproduce the issue in my environment.
Did you login your account in incognito mode?
The tweet might be in private timeline or flagged as sensitive content.

**Comment by borez** [comment]
Thanks - for some reason it's working again. Separately, can I check if there's any way to clear downloaded history in the extension?

**Comment by EltonChou** [comment]
Related feature would be added in the near feature.
Which feature do you prefer? 

1. Clear history.
2. Disable history.
3. Both

**Comment by borez** [comment]
Both would be great! Many thanks for the great work!
