### ISSUE TITLE
[FEATURE]: Drag and drop parts of filename pattern

### ISSUE THREAD

**Issue by Laurens256** [EltonChou/TwitterMediaHarvest#116]
**Is your feature request related to a problem? Please describe.**
Currently, the way to set the filename pattern order is by clicking the boxes in the order you want. This works, but it might be more intuitive if you could drag and drop the boxes to order them. 

**Describe the solution you'd like**
Here's a very quick and dirty sketch of what I mean (don't pay attention to the styling):
![image](https://github.com/EltonChou/TwitterMediaHarvest/assets/85798751/71371612-d73c-487c-884f-6c4494d3b40f)
Above you'd still have the options and you can click them to add or remove them from the list below. Then in the list below, you can drag and drop to reorder the pattern

**Describe alternatives you've considered**
Some variation of this idea where you drag items from the top list instead of clicking, but I think the idea described above is better personally

If you want I could create a pr for this using something like [SortableJs](https://github.com/SortableJS/Sortable). If this is not something you want added, feel free to close the issue :)

**Comment by EltonChou** [comment]
I like this idea, feel free to open the pr.
At first, I want to implement this feature,
but i'm not familiar with drag-drop api and this component was set only once in most of the time.

**Comment by Laurens256** [comment]
Alright, not sure when I'll have time to research / implement this but I will keep you updated
