### ISSUE TITLE
[BUG] Firefox containers cause any download attempts to fail after a while

### ISSUE THREAD

**Issue by cheatreal321** [EltonChou/TwitterMediaHarvest#119]
**Describe the bug**
Staying logged into Twitter for a while inside a Firefox container tab eventually causes all attempts to download a tweet in that container to fail with this error:
![13 11 23_3321_firefox](https://github.com/EltonChou/TwitterMediaHarvest/assets/150494288/d134dad4-bc77-47a4-9a47-b2633792d2c4) 
This can be temporarily fixed by downloading a tweet in a container that's not logged in, or a tweet in a tab without any container. Attempting to download any tweet in a private window while this bug is active will not work and show the same error.
However, for any NSFW tweets which require a login to view a different error persists:
![13 11 23_3322_firefox](https://github.com/EltonChou/TwitterMediaHarvest/assets/150494288/3c9cf765-41c6-4d41-98f9-4cf91b891692)
This can also be fixed temporarily for all containers by logging a Twitter account into a tab without a container, and downloading an NSFW tweet.

**To Reproduce**
1. Install the [Firefox Multi-Account containers addon](https://addons.mozilla.org/en-US/firefox/addon/multi-account-containers/)
2. Create a container using the addon
3. Open a new container tab and use it to log into a Twitter account that is not currently logged in on the same browser.
4. Keep any container tab with the Twitter login open for an extended period.
In my case the bug started to happen a day after I began using containers, however simply causing the tab/tabs to unload or stay inactive for a few hours might be enough. Keeping a tab open at all might not be necessary to recreate it either, since the trigger seems to have simply been time. I'm not really sure.
5. Attempt to download media from any tweet using the container tab with the login to get the error(s).

**Expected behavior**
Tweet media is downloaded without error message, regardless of container or whether the tweet is NSFW or not.

**System info**
 - OS: Windows 10 IoT Enterprise LTSC
 - Browser: Firefox 119.0.1 (64-bit)
 - Version: Media Harvest v4.2.0 (firefox)

**Additional context**
Refreshing the page or cache refreshing with Ctrl + F5 at any point has not helped.

**Comment by EltonChou** [comment]
Duplicated #99.
