### ISSUE TITLE
[FEATURE]  An Option to have the Tweet in the filename

### ISSUE THREAD

**Issue by G1732** [EltonChou/TwitterMediaHarvest#124]
Any way to have the tweet content in the filename.

**Comment by G1732** [comment]
> Filename is not a notepad.

Yes i know but it could be useful to have this option because some tweets have names of the people and some have important text that should in the filename. 
This also helps to keep the downloaded files organized. 

Btw, i just want the extension to save upto 20 letters of the tweet.That would be enough for me. 

Example of tweets:
![bH5f1NKnQ0](https://github.com/EltonChou/TwitterMediaHarvest/assets/152978924/d9272aca-d576-40d1-9450-b9dd0ce2db78)
![1Vu5AQFHby](https://github.com/EltonChou/TwitterMediaHarvest/assets/152978924/6f1bfaad-d82e-46ad-8923-93256526f543)

**Comment by EltonChou** [comment]
There are few things need to be solved.
1. How do you define the `important text` ?
2. The max length of tweet is 280 characters, if you paid you get more. Which part is the important part?

If the content has hashtags, it would be recorded in database and you can search the tags in options page.
This feature would be release in the future.

**Comment by G1732** [comment]
> There are few things need to be solved.
> 
> 1. How do you define the `important text` ?
> 2. The max length of tweet is 280 characters, if you paid you get more. Where is the important part?
> 
> If the content has hashtags, it would be recorded in database and you can search the tags in options page. This feature would be release in the future.

1. There is no need to define the important text because that would be impossible, the extension should simply save the tweet text content in the filename. For example the photo of the owl in my post above should have the filename as :

"Barn Owl (photo by Michal Ninger).jpg" . 

This helps in keeping downloaded files organized.


2. Upto 280 characters is more than enough, 
if it can save 50 characters of a tweet in the filename thats more than enough for me.

**Comment by EltonChou** [comment]
You didn't get the point.
This is your scenario not everyone's.

How do you deal with this three different formats below?
```
BruhBruhBruhBruhBruhBruhBruh
BruhBruhBruhBruhBruhBruhBruh
BruhBruhBruhBruhBruh
Barn Owl (photo by Michal Ninger)
FoobarFoobarFoobarFoobarFoobar
FoobarFoobarFoobarFoobarFoobar
```
```
Barn Owl (photo by Michal Ninger)
BruhBruhBruhBruhBruhBruhBruh
BruhBruhBruhBruhBruhBruhBruh
BruhBruhBruhBruhBruh
FoobarFoobarFoobarFoobarFoobar
FoobarFoobarFoobarFoobarFoobar
```
```
BruhBruhBruhBruhBruhBruhBruh
BruhBruhBruhBruhBruhBruhBruh
BruhBruhBruhBruhBruh
FoobarFoobarFoobarFoobarFoobar
FoobarFoobarFoobarFoobarFoobar
Barn Owl (photo by Michal Ninger)
```

The most of operating systems restrict the length of filename length to less or equal to 255 characters.
What if the content length is over 255? 
Remember that you have to keep the filename as unique, so you still need other filename patterns.

**Comment by G1732** [comment]
> You didn't get the point. This is your scenario not everyone's.
> 
> How do you handle three different formats below?
> 
> ```
> BruhBruhBruhBruhBruhBruhBruh
> BruhBruhBruhBruhBruhBruhBruh
> BruhBruhBruhBruhBruh
> Barn Owl (photo by Michal Ninger)
> FoobarFoobarFoobarFoobarFoobar
> FoobarFoobarFoobarFoobarFoobar
> ```
> 
> ```
> Barn Owl (photo by Michal Ninger)
> BruhBruhBruhBruhBruhBruhBruh
> BruhBruhBruhBruhBruhBruhBruh
> BruhBruhBruhBruhBruh
> FoobarFoobarFoobarFoobarFoobar
> FoobarFoobarFoobarFoobarFoobar
> ```
> 
> ```
> BruhBruhBruhBruhBruhBruhBruh
> BruhBruhBruhBruhBruhBruhBruh
> BruhBruhBruhBruhBruh
> FoobarFoobarFoobarFoobarFoobar
> FoobarFoobarFoobarFoobarFoobar
> Barn Owl (photo by Michal Ninger)
> ```
> 
> The most of operating systems restrict the length of filename length to less or equal to 255 characters. What if the content length is over 255? Remember that you have to keep the filename as unique, so you still need other filename patterns.

I would save the three formats as they are because 
they contain the important text "Barn Owl (photo by Michal Ninger)."

As for the character length of the filename, if it is over 255 characters then the extension should save upto 255 and ignore the rest of the characters.


And in order to keep the filename unique i would use  "Tweet ID" or "Hash" options in Filename Pattern.

**Comment by G1732** [comment]
> > As for the character length of the filename, if it is over 255 characters then the extension should save upto 255 and ignore the rest of the characters.
> 
> If the `important text` is located at somewhere > 255 characters, how do you handle it? Your filename will be `{tweet id}-{hash}-{a lot of text without important text}.{ext}`.

If some filenames are saved without the important text, its okay.

**Comment by EltonChou** [comment]
Then those texts are not important.
If you want this feature you can fork it and implement by yourself.

**Comment by G1732** [comment]
> Then those texts are not important. If you want this feature you can fork it and implement by yourself.

Well, Okay. 

Atleast give your suggestion on how you would have 
solved this.

**Comment by G1732** [comment]
> I will provide a regex token for advanced user in the future, but the user needs to know how to write a valid regular expression.

Regex token meaning the tweet contents will be saved 
in the downloads page of the extension or a separate txt file.

**Comment by G1732** [comment]
> I will provide a regex token for advanced user in the future, but the user needs to know how to write a valid regular expression.

Sorry i am a bit confused can you please elaborate.

Using regex how will a user save the important text in this tweet.

 BruhBruhBruhBruhBruhBruhBruh
BruhBruhBruhBruhBruhBruhBruh
BruhBruhBruhBruhBruh
Barn Owl (photo by Michal Ninger)
FoobarFoobarFoobarFoobarFoobar
FoobarFoobarFoobarFoobarFoobar


I just want to know.

**Comment by G1732** [comment]
One last thing, what will be the regex for this tweet :

![image](https://github.com/EltonChou/TwitterMediaHarvest/assets/152978924/c20553d7-6581-4672-b663-9bb0b0752376)

**Comment by EltonChou** [comment]
You should try it by yourself.
https://regex101.com/
