### ISSUE TITLE
[BUG]Filename corrupted, and file not in the correct folder

### ISSUE THREAD

**Issue by ericbig66** [EltonChou/TwitterMediaHarvest#125]
**Describe the bug**
The download wasn't renamed correctly, and I'm sure I only enable one download management extension.
This is a new issue after X update their media page layout.

**To Reproduce**
1. Go to [https://twitter.com/TheFeelGo0dPage/status/1733676678021587398/](url)
2. Click on 'download button'
3.  In "twitter media harvest" folder the file is not there, and with a corrupted filename, all the settings are still there but nolonger functional anymore

**Expected behavior**
file named as set, file in the folder as set

**Desktop (please complete the following information):**
 - OS: windows 10
 - Browser: Edge 
 - Version: 119.0.2151.93

**Comment by EltonChou** [comment]
Please ensure that you only enable one install management extension or it would be race condition.
Or you can turn on the aggressive mode in the options page.

**Comment by EltonChou** [comment]
No further response.

**Comment by ericbig66** [comment]
I've tried aggressive mode but still not working properly, and reinstall is
not working either

Elton H.Y. Chou ***@***.***> 於 2023年12月17日 週日 下午9:59寫道：

**Comment by EltonChou** [comment]
> I've tried aggressive mode but still not working properly, and reinstall is not working either 
I can't reproduce the issue.
Can you share your filename pattern setting and the filename result?
