### ISSUE TITLE
[FEATURE] An option to choose the default path, is driving me crazy.

### ISSUE THREAD

**Issue by Gitphex** [EltonChou/TwitterMediaHarvest#131]
**Is your feature request related to a problem? Please describe.**
An option to choose the default path, is really driving me crazy, even if i choose manually where to download and setup as not to ask, it always download the files in a default directory that is in Documents in C: and i don't have space.

**Describe the solution you'd like**
To be able to choose the default path for downloaded files, even if it ask or not.

**Describe alternatives you've considered**
none.

**Additional context**
nothing.

**Comment by EltonChou** [comment]
> **Is your feature request related to a problem? Please describe.** An option to choose the default path, is really driving me crazy, even if i choose manually where to download and setup as not to ask, it always download the files in a default directory that is in Documents in C: and i don't have space.
> 
> **Describe the solution you'd like** To be able to choose the default path for downloaded files, even if it ask or not.
> 
> **Describe alternatives you've considered** none.
> 
> **Additional context** nothing.

This is browser's settings, please change the settings in your browser.

[Chromium](chrome://settings/downloads)
[Firefox](about:preferences)

**Comment by Gitphex** [comment]
> This is browser's settings, please change the settings in your browser.
> 
> Chromium: `chrome://settings/downloads` Firefox: `about:preferences`

I'm on FireFox, it worked thank you so much, i think it was because i had it in an HDD that was removed and then when that unite wasn't find the default path was reset to the C:.

But still, it could be great to add an option in the plugin settings i think.

Thanks and greetings.

**Comment by EltonChou** [comment]
> But still, it could be great to add an option in the plugin settings i think.
The browser only allow extension to control the *relative* path under `default download directory`.
A tip to control flexibly the file location is using symbolic link. I think most of OS support this feature.
