### ISSUE TITLE
[BUG]-download type

### ISSUE THREAD

**Issue by bob2cc1** [EltonChou/TwitterMediaHarvest#141]
**Describe the bug**
If the download wasn't renamed correctly, please ensure you only enable one download management extension.
This is a known issue on chromium based browser.

The images are downloading in orig file format 

**To Reproduce**
1. Go on twitter
2. download image by clicking the download button
3. try to open image

**Expected behavior**
download in jpg/png

**Screenshots**

**Desktop (please complete the following information):**
 - OS: windows 11 
 - Browser: chrome
 - Version: Version 123.0.6312.86 (Official Build) (64-bit)

**Additional context**

**Comment by EltonChou** [comment]
Did you read the issue template?
