### ISSUE TITLE
Not saving automatically on Brave Browser

### ISSUE THREAD

**Issue by RickyM017** [EltonChou/TwitterMediaHarvest#144]
I tried using it on Brave but the media is not saving automatically in the folder unlike chrome. It always prompt on where to save. Is there a way to solve this? Is there a way for it to work same as in chrome

**Comment by EltonChou** [comment]
Go to the settings and disable `Ask where to save each file before downloading` or any something like this.

**Comment by RickyM017** [comment]
Thank you.
