### ISSUE TITLE
[BUG] Not downloading anything.

### ISSUE THREAD

**Issue by madhatr** [EltonChou/TwitterMediaHarvest#145]
I went to [this URL](https://twitter.com/tracygialx) (nsfw) and hit the D key, nothing happens.  I go directly into a post and try again and no downloads start.

**Screenshots**
![image](https://github.com/EltonChou/TwitterMediaHarvest/assets/14855242/65fb3ecb-80ef-44fa-a814-435b53b11b46)
![image](https://github.com/EltonChou/TwitterMediaHarvest/assets/14855242/b5f94c77-9d2e-44de-918e-823d6a4638ab)

Win 11

**Comment by EltonChou** [comment]
You need to use `J` `K` to navigate tweet then press `D` to download.

**Comment by madhatr** [comment]
Thank you,  I didn't realized I needed to hit J and K to select.   It is working well.
