### ISSUE TITLE
[BUG] download button suddenly doesn't show up

### ISSUE THREAD

**Issue by MinamikoAAAA** [EltonChou/TwitterMediaHarvest#146]
The download button suddenly doesn't show up. The shortcut "D" also doesn't work.

Chrome 124.0.6367.158

There's probably a way to reset the add-on, I could use a quick guide ...

**Comment by MinamikoAAAA** [comment]
Tried: clear cookies, log out from twitter, then log in
          re-install twitter media harvester add-on
          couldn't solve the issue

**Comment by Starayo** [comment]
Also having this issue on a fresh install, was trying after the change today that forces twitter.com links to x.com now broke the scripts I was using previously.

Shortcuts J/K to select tweets work, but no download button and D doesn't do anything.

**Comment by EltonChou** [comment]
> The download button suddenly doesn't show up. The shortcut "D" also doesn't work.
> 
> Chrome 124.0.6367.158
> 
> There's probably a way to reset the add-on, I could use a quick guide ...

Have you installed any extension which may change twitter's layout?

**Comment by Starayo** [comment]
> > Also having this issue on a fresh install, was trying after the change today that forces twitter.com links to x.com now broke the scripts I was using previously.
> > Shortcuts J/K to select tweets work, but no download button and D doesn't do anything.
> 
> After install, you need to refresh the page.

I have done that, no change.

I have also tested on a new profile to prevent any other addons or scripts interfering with it. Fresh profile with nothing but media harvest installed, same problem. No button, J/K works, D does nothing. Extension doesn't seem to be having any visible effect as J/K works with it disabled, I see now it's a default twitter keyboard shortcut.

**Comment by EltonChou** [comment]
Maybe twtiter has pushed some updates to your client. The extension works well in my environment.
Is there any error message showed in the console or extension?

**Comment by birtchh** [comment]
> Maybe twtiter has pushed some updates to your client. The extension works well in my environment. Is there any error message showed in the console or extension?

I tried turning off all my extensions that affected twitter, including control panel for twitter and ublock, this is the error message in the console 

![ESygqn1PLD](https://github.com/EltonChou/TwitterMediaHarvest/assets/169874967/0cb8d6ac-7b0e-4ce4-bd9a-bd6edd0ae689)

and the log 
[x.com-1715828002243.log](https://github.com/EltonChou/TwitterMediaHarvest/files/15329253/x.com-1715828002243.log)

The download button is no longer there, this seemed to only start when twitter keeps being redirected to x.com, this seemed to affect all posts, on the timeline and on the post page too.
(sry if im missing anything im new at this Y_Y)

**Comment by Starayo** [comment]
> Maybe twtiter has pushed some updates to your client. The extension works well in my environment. Is there any error message showed in the console or extension?


Mine's the same as above, nothing in console except the third-party cookie warnings. No error in the extension that I can find.

With the timing, it probably does have something to do with when they started forcing redirection to x.com for my region (Australia) recently. Previously I was still accessing it via twitter.com.

**Comment by yuuma0** [comment]
> > Maybe twtiter has pushed some updates to your client. The extension works well in my environment. Is there any error message showed in the console or extension?
> 
> Mine's the same as above, nothing in console except the third-party cookie warnings. No error in the extension that I can find.
> 
> With the timing, it probably does have something to do with when they started forcing redirection to x.com for my region (Australia) recently. Previously I was still accessing it via twitter.com.

A temporary solution you could do is use a VPN while accessing via twitter.com, can confirm that it still works. I think it is a gradual rollout for the force redirection and australia being one of the first ones to get redirected. 

I also assume that the API on x.com is different from twitter.com which might be causing it to disappear?

**Comment by komoreshi** [comment]
> A temporary solution you could do is use a VPN while accessing via twitter.com, can confirm that it still works. I think it is a gradual rollout for the force redirection and australia being one of the first ones to get redirected.
> 
> I also assume that the API on x.com is different from twitter.com which might be causing it to disappear?
> 
> edit: you don't have to keep the VPN on at all times, I think you can go without it after the website loads bypassing the forced redirect

As long as the page isn't refreshed after disconnecting, it works fine. Given the new domain will eventually be rolled out to everyone, it'll still warrant a fix at some stage.

**Comment by EltonChou** [comment]
> As long as the page isn't refreshed after disconnecting, it works fine. Given the new domain will eventually be rolled out to everyone, it'll still warrant a fix at some stage.

I need find a way to simulate the behavior. Is there any reliable public Australia VPN service?
In my environment, the `x.com` would be directed to `twitter.com` and it works fine.

**Comment by komoreshi** [comment]
Normally wouldn't recommend a free VPN, but ProtonVPN should work for testing - just create a burner account. New Zealand is also redirecting in addition to Australia.

**Comment by komoreshi** [comment]
Not that I recommend using free VPNs, but if it's just for testing, something like TunnelBear might work as they have AU servers.

**Comment by EltonChou** [comment]
Root cause
https://github.com/EltonChou/TwitterMediaHarvest/blob/4976253a70096f6417e2279b093fe399c16ea570/src/content_script/utils/checker.ts#L20

I will push update soon.
Thanks for providing information.

**Comment by EltonChou** [comment]
[v4.2.5](https://github.com/EltonChou/TwitterMediaHarvest/releases/tag/v4.2.5)

It will take few days to pass the store verification.

**Comment by Dark-Decay** [comment]
> It will take few days to pass the store verification.
Is this why there isn't an `.xpi` for the Firefox release of v4.2.5 yet? I'm not familiar with how the process works.

**Comment by EltonChou** [comment]
> Is this why there isn't an `.xpi` for the Firefox release of v4.2.5 yet? I'm not familiar with how the process works.

I have uploaded it. Check release page.
