### ISSUE TITLE
[FEATURE]About the created or modified date of the file

### ISSUE THREAD

**Issue by countdown88** [EltonChou/TwitterMediaHarvest#151]
Is there a way to sort downloaded files in the order of created or modified dates?

For example, today (May 17, 2024), download the file tweeted May 17, 2023.

At this time, I would like to download a file with the date created or modified date of May 17, 2023.

I want to sort the pictures in order from the past, I think it's saved as the time I downloaded it

Is there an option to sort by tweeted time line?

**Comment by EltonChou** [comment]
This is file explorer's job.

**Comment by m1n1vv** [comment]
> This is file explorer's job.

This can be implemented using JSZip.js.  All files from each tweet will be in the archive. The time the post was created can be written to the date of the last modification.

**Comment by EltonChou** [comment]
> This can be implemented using JSZip.js. All files from each tweet will be in the archive. The time the post was created can be written to the date of the last modification.

I knew there are many ways to implement this feature.
But in my opinion, an extension is not a good place to do this job.
