### ISSUE TITLE
[BUG] Can't Export History from Firefox 4.2.0 Version

### ISSUE THREAD

**Issue by EricPTG** [EltonChou/TwitterMediaHarvest#152]
**Describe the bug**
I used the latest .xpi file to update my Media Harvest Firefox extension from 4.2.0 to 4.2.5, but both versions are listed as separate entries and I can't seem to get my download history to export from the 4.2.0 version. I referenced this page from another user:https://github.com/EltonChou/TwitterMediaHarvest/issues/139 but when entering the export command into the console I get an error every time.

**To Reproduce**
1. Go to the Media Harvest Extension History page
2. Open Firefox's Console and paste "await browser.runtime.sendMessage({action: 4})"
3. See error

**Expected behavior**
From my understanding I should be given a JSON file to import into the 4.2.5 version of the extension.

**Screenshots**
![image](https://github.com/EltonChou/TwitterMediaHarvest/assets/114555986/17a235c0-3edb-4166-862a-dd2316b48f35)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Firefox 126.0 (64-bit)
 - Extension Version: 4.2.0

**Comment by EltonChou** [comment]
`v4.2.0` doesn't have history exporting feature and this feature is for development usage.

**Comment by EricPTG** [comment]
Unfortunate to hear. Is there anyway to transfer the data between versions then or should I just start off fresh?

**Comment by EltonChou** [comment]
The history was stored in the Indexed DB.
If you know how to manipulate it, you can export the history easily.

**Comment by EricPTG** [comment]
Sounds good. Thank you for your help!
