### ISSUE TITLE
[BUG] Twitter Media Harvest does not work on x.com

### ISSUE THREAD

**Issue by SolventMercury** [EltonChou/TwitterMediaHarvest#154]
Twitter recently switched its URL to x.com, and if you attempt to open a new tab and navigate to the old Twitter URL, you will automatically be redirected to x.com. On x.com, Twitter Media Harvest does nothing at all. The interface elements for downloading media do not appear and the entire plugin doesn't really have any effect while on x.com.

**Comment by EltonChou** [comment]
See #150
