### ISSUE TITLE
[FEATURE]

### ISSUE THREAD

**Issue by m1n1vv** [EltonChou/TwitterMediaHarvest#155]
Is it possible to add download buttons to the media?

**Example:**
![2024-05-17_203031](https://github.com/EltonChou/TwitterMediaHarvest/assets/19503023/d98de449-02ca-47c4-b1cd-51c264c955df)

**Comment by EltonChou** [comment]
Duplicated #126

**Comment by m1n1vv** [comment]
> Duplicated #126

I'm a little different. Being able to download directly from the media page.

**Comment by EltonChou** [comment]
Upload?
I suppose you are saying download.
https://github.com/EltonChou/TwitterMediaHarvest/issues/126#issuecomment-1852762503
