### ISSUE TITLE
[FEATURE]

### ISSUE THREAD

**Issue by talran** [EltonChou/TwitterMediaHarvest#156]
Currently "gif" posts download as .mp4 files.

Ideally we would be able to convert those posts on download to .gif

There's another extension below that does such, and I'd be interested in requesting the feature or working on it on the side to implement into this addon so that I don't have to run both:

https://addons.mozilla.org/en-US/firefox/addon/twitter-media-assist-ff/

**Comment by EltonChou** [comment]
It was `gif`. There is no gif file in server.
Twitter always converts them into `mp4` and do converting task in an extension is inefficient.
