### ISSUE TITLE
[FEATURE] Each file in the folder with the author's name

### ISSUE THREAD

**Issue by m1n1vv** [EltonChou/TwitterMediaHarvest#160]
Is it possible to make files saved to a folder with the author's name instead of a shared folder? And this feature can be enabled/disabled in the extension panel.

**For example:**
`twitter_media_harvest/@username/username-16416416516565484-01`

I've done it in php, but I don't want to spend time on it.

**Comment by EltonChou** [comment]
Go to the options page you will find some useful options.
