### ISSUE TITLE
[FEATURE] Download media in Chrome incognito mode

### ISSUE THREAD

**Issue by MtZero** [EltonChou/TwitterMediaHarvest#161]
**Is your feature request related to a problem? Please describe.**
Is it possible to download media in Chrome incognito mode?
The download icon will turn red and do nothing after clicking it.

**Describe the solution you'd like**
The media can be downloaded normally as usual as in normal window.

**Comment by EltonChou** [comment]
What version did you use? Is there any error message?
If you allow the extension to runs in incognito mode, it should work.

**Comment by MtZero** [comment]
> What version did you use? Is there any error message? If you allow the extension to runs in incognito mode, it should work.

Thank you for replying.
It doesn't work on version 4.2.5, but it's okay on 4.2.6 updated manually, seems due to download issue on 4.2.5.
Case could be closed :-)
