### ISSUE TITLE
[BUG] Not working | Many Error's .

### ISSUE THREAD

**Issue by TareqAbAmawi** [EltonChou/TwitterMediaHarvest#162]
**Describe the bug**
- Image save as not support format " Ex : ._org "
- video/image saved as random name " This is very annoying. In previous versions, the Twitter username was added to the beginning of the downloaded file. "
- Sometimes the download option appears on the tweet and sometimes it does not appear .

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Browser: Vivaldi
 - Version 6.7.3329.26

**Comment by EltonChou** [comment]
Don't install download-management extension more than one, it will cause race condition.
