### ISSUE TITLE
[BUG] Downloading in Chrome stopped working after update 4.2.7

### ISSUE THREAD

**Issue by MeiHouwang** [EltonChou/TwitterMediaHarvest#165]
After version update 4.2.7 all image downloads stopped working, now after pressing on download button it turns red and downloads nothing.
![image](https://github.com/EltonChou/TwitterMediaHarvest/assets/11078863/14f7b21c-acfe-4869-b1c5-dc2c9041b48f)

**Comment by EltonChou** [comment]
Where is your ip geolocation?
Is there any error notification?

**Comment by EltonChou** [comment]
> Sorry, it seems like it was some unrelated network issues. Today everything works as usual. Seems like it just happened the same time as plugin updated.

Sometimes you need to reload the page.
The script injected in page might be still in older version.
