### ISSUE TITLE
[FEATURE] option to save file to last location

### ISSUE THREAD

**Issue by parsue** [EltonChou/TwitterMediaHarvest#166]
**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like**
Currently save to download folder, it is convenient to people who set browser not ask where to save.
I like to manage files when I download it.  if there are multiple files in batch, I need to select location few times to save.

**Describe alternatives you've considered**
An option to remember last save location.

**Comment by EltonChou** [comment]
A download request may contains several files.
And all downloads are emitted at same time. 
You have to select the location manually per file if you want to manage the location.
