### ISSUE TITLE
[BUG] Unable to download using Cromite browser

### ISSUE THREAD

**Issue by Aquazu** [EltonChou/TwitterMediaHarvest#169]
**Describe the bug**
Getting a "TwitterApiError: Your login session might be expired, please refresh your page.(statusCode: 403)"
when trying to download images/videos using a browser named Cromite. Because both chrome and cromite are made on chromium, i assume this is a bug.

**To Reproduce**
1. Download Cromite at https://github.com/uazo/cromite
2. Install the TwitterMediaHarvest extension on the cromite browser, either by using a zip-file or using the Chrome web store.
3. go to twitter/x, and find any post to download from
4. Result is the StatusCode 403

**Expected behavior**
Getting my videos/images dowloaded.

**Screenshots**
Expected result on edge:
![image](https://github.com/EltonChou/TwitterMediaHarvest/assets/22175546/a73475b3-920b-4d1f-af78-a4b0df154e42)
![image](https://github.com/EltonChou/TwitterMediaHarvest/assets/22175546/25c5d4e4-a81c-4227-be2a-d3964c372f29)

Results on Cromite:
![image](https://github.com/EltonChou/TwitterMediaHarvest/assets/22175546/da34d6c7-3dbc-488d-8c1a-c6e745e67a3d)
![image](https://github.com/EltonChou/TwitterMediaHarvest/assets/22175546/3be63d39-1e4e-4cb3-9e80-536175a34175)

**Desktop (please complete the following information):**
 - OS: Windows 10, 22H2
 - Browser: Cromite
 - Version 4.2.7

**Additional context**
Cromite is a privacy-first browser. Perhaps this is what's making it block certain data from being sent to the extension?
I'm uncertain where i should be posting this, so i'm trying it here first.

**Comment by Aquazu** [comment]
I am logged in to my twitter/x account yes

I am unsure what you mean by 'ip geo location', could you explain where i could find this info?
Perhaps image below is what you're looking for?
![image](https://github.com/EltonChou/TwitterMediaHarvest/assets/22175546/ff1abeac-947d-456e-9476-0448c6a0d9d8)

**Comment by EltonChou** [comment]
Where are you? America, France, Germany or something else?

**Comment by EltonChou** [comment]
This extension use your twitter session cookies to download.
It seems that Cromite prohibits this behavior.

**Comment by RSerejo** [comment]
i'm having this problem using firefox/waterfox

**Comment by RSerejo** [comment]
i reinstalled and then it fixed
