### ISSUE TITLE
file rename incorretly and unable to save file corretly[BUG]

### ISSUE THREAD

**Issue by minecraftyusei** [EltonChou/TwitterMediaHarvest#170]
i am using google translation,sorry for my english.

**Describe the bug**
Unable to save the file to the program's default folder "twitter media harvest" but save file in the google default folder. 

And the name of the picture changed. "_orig" appears in the filename, and changes filename like that: GPiagoqbUAA8_NW.jpg------GPiagoqbUAA8_NW,jpg_orig

I am sure I have never changed the settings of the program and in my chrome there is no other download program work.

**To Reproduce**
1. Go to 'chromewebstore'
2. Install the TwitterMediaHarvest extension on the  browser
3. go to twitter/x, and find any post to download from
4. the file was renamed like "GPiagoqbUAA8_NW,jpg_orig" and was saved to the google default folder but not the folder"twitter media harvest"

**Expected behavior**
Getting my videos/images renamed and downloaded correctly.

**Screenshots**
![屏幕截图 2024-06-08 180122](https://github.com/EltonChou/TwitterMediaHarvest/assets/39985294/cabfe08f-ea2e-42dd-beee-694081462e1d)
as you can see,I click download just several minutes ago, and it was renamed like this and this picture was saved into "googledownload", which is my default download folder for Google.

**Desktop (please complete the following information):**
 - OS: win11,23H2
 - Browser:chrome
 - Version:4.2.7

**Additional context**

**Comment by EltonChou** [comment]
Please temporarily disable other extensions then try again.
It will cause race condition if any extension use this [API](https://developer.chrome.com/docs/extensions/reference/api/downloads#event-onDeterminingFilename)

**Comment by minecraftyusei** [comment]
> Please temporarily disable other extensions then try again. It will cause race condition if any extension use this [API](https://developer.chrome.com/docs/extensions/reference/api/downloads#event-onDeterminingFilename)

Thank you for your reply! The filename seems to be right!

**Comment by mimilee33** [comment]
this bug is not solved, please check this issue ,thanks

OS:windows 11 24H2
chrome：136.0.7103.93
media harvest：4.4.1

![Image](https://github.com/user-attachments/assets/76bfa48c-2bff-441b-abf3-f7f7197d64e5)

**Comment by mimilee33** [comment]
> Please temporarily disable other extensions then try again. It will cause race condition if any extension use this [API](https://developer.chrome.com/docs/extensions/reference/api/downloads#event-onDeterminingFilename)

It didn't work

<img width="226" alt="Image" src="https://github.com/user-attachments/assets/977cbb55-70fd-4d34-8e79-51be35b57cd9" />
![Image](https://github.com/user-attachments/assets/5a9f0722-289d-4620-a9f5-0ff8b0283947)

**Comment by EltonChou** [comment]
This is not bug this is feature by chromium. Check other extension's setting. Not this extension's settings.
Also check #187

**Comment by erbanku** [comment]
https://github.com/EltonChou/TwitterMediaHarvest/issues/187#issuecomment-3254211695
