### ISSUE TITLE
[FEATURE] Alter filename patterns

### ISSUE THREAD

**Issue by MarkoNoa** [EltonChou/TwitterMediaHarvest#172]
**Is your feature request related to a problem? Please describe.**
Not really. Thanks for this awesome extension!

**Describe the solution you'd like**
The current filename pattern I use is Account-Tweetdate-TweetID-Serial. Just wondering if I can change the format to how I would like.
eg. Tweetdate 20220202 to 2022.02.02 and serial is 01-04, I'd like it to be single digit 1-4 don't see a reason to uses two digits. Is there a easy way that I can change those myself. Much appreciated.

**Describe alternatives you've considered**

**Additional context**

**Comment by EltonChou** [comment]
Please check this [thread](https://stackoverflow.com/questions/3926324/dot-in-file-name) about dot in filename.

Nobody can promise that twitter will not allow more medias in one tweet in the future.
Preserving two digits can prevent this situation. Unless twitter allows medias that can be more than 99 in one tweet.

I sugget that you can use some batch-rename tools to alter the filename.

**Comment by EltonChou** [comment]
Since `.` in filename might cause unexpected errors that can't be handled by this extension.
This issue would be closed.
