### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by SparklingMonarch** [EltonChou/TwitterMediaHarvest#175]
idk if its supposed to be like that but all pictures i downloaded are a "JPG_ORIG" file and my normal windows media app cant detect or show these
 i simply clicked the download button and dont rly changed anything in the settings or found a setting to fix it.
**Expected behavior**

**Screenshots**

i use Opera GX browser on Windows 11
![Bild_2024-07-09_201024583](https://github.com/EltonChou/TwitterMediaHarvest/assets/128073008/4a86af41-8b70-4551-acce-8f46f263c6e8)

("Datei" is just "filetype" in my language so dont mind that word)

**Comment by EltonChou** [comment]
Please check #170.
