### ISSUE TITLE
[BUG] Media Harvest stopped working on Firefox

### ISSUE THREAD

**Issue by razeNFR** [EltonChou/TwitterMediaHarvest#176]
Hello,

Today MediaHarvest stopped working on firefox, im unable to download image and video.

**Comment by EltonChou** [comment]
It works properly in my environment.
Please provide more information.

Does the button disappears? or it turn red after you click it?
Is there any error message?
Where is your ip geolocation?

**Comment by UNordicc** [comment]
Hi.
I'll prob give some info about the problem. At the time of writing this comment (around 2PM CEST) Harvest is having a problem with login session. Refreshing X/Twitter website and restarting Firefox doesn't fix an issue. For some more info, my IP geolocation is Poland and after clicking a button it turns red as answer for following question from @EltonChou 
![Zrzut ekranu_20240718_134446](https://github.com/user-attachments/assets/efa284c9-b547-47ce-83a8-82c292675d32)

**Comment by EltonChou** [comment]
Thanks for the detail !
Which version of Firefox do you use?

**Comment by UNordicc** [comment]
> Which version of Firefox do you use?

126.0.1

**Comment by UNordicc** [comment]
Seems like X/Twitter just made some updates that restricted and/or changed location of some features that Harvest used. Currently, OldTwitter by dimdenGD is also struggling with issues https://github.com/dimdenGD/OldTwitter/issues/889

**Comment by EltonChou** [comment]
I can't reproduce this error in my environment. (Firefox 127.0, Media Harvest v4.2.7).
Can you try the chrome version? If they changed something, you should get same error.

**Comment by UNordicc** [comment]
> Can you try the chrome version?

For Chrome version testing I've used Brave 1.67.134 with Harvest v4.2.7 (chrome).
No issues found. It might be an extension problem itself on Firefox.
How can I help you more to diagnose the problem?

**Comment by UNordicc** [comment]
Ok issue located. OP prob didn't update his Harvest to the newest one (v4.2.7) same as me.
As long OP don't answer, issue can be closed.

**Comment by EltonChou** [comment]
I think that I need a better way to notify Firefox self-signed version users when the newer version published.
It's good to know the issue was solved, thanks for your feedbacks !
