### ISSUE TITLE
可以点击下载键后自动点击喜欢么♥

### ISSUE THREAD

**Issue by FulanScarlet** [EltonChou/TwitterMediaHarvest#177]
![Screenshot_2024-07-17-23-08-56-40_4d38fce200f96aeac5e860e739312e76](https://github.com/user-attachments/assets/40be95bb-668b-48f4-9444-5d889834dbfc)
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by EltonChou** [comment]
下載按鈕不應該有副作用
