### ISSUE TITLE
[FEATURE]Download the tweet text, and download tweet without media

### ISSUE THREAD

**Issue by menduo** [EltonChou/TwitterMediaHarvest#178]
**Is your feature request related to a problem? Please describe.**
No.

**Describe the solution you'd like**
Also download the tweet text. I think the filename should be '{pattern}'-tweet.txt/md.

And the other side, I'd like to download the tweet without any media, just the tweet text only. 

There's a problem we should think about that is the file name pattern, by default the  file is sort by filename A-Z, the tweet text file should be at front of the media files, just like:

```
{username}-{date}-{tweet_id}-000.txt
{username}-{date}-{tweet_id}-{no}.jpg
```

The text file will be on the top, we read the tweet first, then we preview the media files.

Thank you for the great extension ❤️

**Describe alternatives you've considered**
No.

**Additional context**
No.

**Comment by EltonChou** [comment]
This is media downloader.
What you need is a simple user script and  a database which is supporting full-text search.

**Comment by menduo** [comment]
> This is media downloader. What you need is a simple user script and a database which is supporting full-text search.

@EltonChou I mean the text is the description of the media files, I don't need an database, just get the media with it's descrtion together,  sometimes the description is very import to explain the media.

I hope I made it clear.

Thank you for you reply.
