### ISSUE TITLE
The extension is changing the file extension of the downloaded files rendering the files unusable until we manually change them back[BUG]

### ISSUE THREAD

**Issue by canaryinadigitalmine** [EltonChou/TwitterMediaHarvest#180]
**Describe the bug**
If the download wasn't renamed correctly, please ensure you only enable one download management extension.
This is a known issue on chromium based browser.

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Additional context**

**Comment by EltonChou** [comment]
Not a bug, it is a `feature` by chromium.
You have already answered the question by youself.

**Comment by canaryinadigitalmine** [comment]
> Not a bug, it is a **feature** by chromium. You have already answered the question by youself.

Thank you very much! I found that once I reinstalled the extension the file extensions then became correct again. 

Have a good one! :)

**Comment by EltonChou** [comment]
Last installed will win the file naming battle.
