### ISSUE TITLE
[BUG] Certain Videos dont download for some reason

### ISSUE THREAD

**Issue by FevilGitHub** [EltonChou/TwitterMediaHarvest#183]
**Describe the bug**
Its been a bit of an issue that certain videos occasionally dont download, and im forced to use another downloader.

**To Reproduce**
1. Go to tweet
2. Click on download
3. Nothings Downloaded

**Expected behavior**
Should have downloaded

**Screenshots**
![image](https://github.com/user-attachments/assets/fa7e3c03-edc6-4870-9871-82e04a63b025)
[tried to download this video for sharing ease but the twitter username never popped up and thus never downloaded]

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Browser Microsoft Edge 
 - Version 127.0.2651.98

**Additional context**
Occasionally i try to download a twitter video (memes, stuff i like, etc) but it shows "it downloaded!" but when i try to find it it isnt downloaded at all. i have no idea whats causing this issue but its been bugging me

If you need a list of extensions im using i can provide it whenever necessary.

**Comment by EltonChou** [comment]
![image](https://github.com/user-attachments/assets/c250b61e-8ecf-425e-a350-b44f25486684)

Works properly in my environment.
I suggest that you can temporarily disable all of other extensions and test it again.

**Comment by RickyM017** [comment]
It happens to me also; I disabled or removed extensions, and still some are not downloading.

**Comment by EltonChou** [comment]
Might be related with #182 .

**Comment by FevilGitHub** [comment]
might be! I looked at it too and they seemed to have the same issues as i do, with more technical stuff behind it (im not tech savvy)
