### ISSUE TITLE
[BUG] Sometimes, videos won't be downloaded, even the button becomes green

### ISSUE THREAD

**Issue by Gabarito007** [EltonChou/TwitterMediaHarvest#186]
**Describe the bug**
Sometimes, videos won't be downloaded, even the button becomes green

**To Reproduce**
1. Go to this post: https://x.com/hoje_no/status/1827609461285933355
2. Click on download icon
3. Wait the start of download
4. Download won't start

**Expected behavior**
File downloaded

**Desktop (please complete the following information):**
 - OS: Windows 7
 - Firefox
 - Version 115.12.0

Thanks.

**Comment by EltonChou** [comment]
Please download latest version in release page.

**Comment by Gabarito007** [comment]
Solved!
Thanks.
