### ISSUE TITLE
[BUG] No download button for this tweet

### ISSUE THREAD

**Issue by fireattack** [EltonChou/TwitterMediaHarvest#191]
**Describe the bug**

This post has no download button.

**NSFW** https://x.com/archplum/status/1834231309142737374

If you view the same tweet in the author's timeline, it does have download button. But not in single tweet view.

**To Reproduce**
1. Open **NSFW** https://x.com/archplum/status/1834231309142737374

**Expected behavior**

**Screenshots**

![image](https://github.com/user-attachments/assets/108d6155-e4a6-4ed5-8579-7ef006007ed0)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser Chrome 
 - Version 128.0.6613.137 (Official Build) (64-bit) (cohort: M128 Rollout)

**Comment by EltonChou** [comment]
Checker got the wrong url.
I will fix this ASAP.
