### ISSUE TITLE
[BUG] Images downloading as ORIG files with incorrect names

### ISSUE THREAD

**Issue by NiTROACTiVE** [EltonChou/TwitterMediaHarvest#194]
So I recently been having an issue with Media Harvest, as files download as ORIG files.

For example, when I try to download a PNG image, not only do I not get a PNG file in the name format "tweetUser-1145141919810-02", I get a file named something like "GYlBjZZXMAAdSLZ.png_orig".

I tried uninstalling the extension and reinstalling it, but that didn't work.

Does anyone know what the issue could be?

**Comment by EltonChou** [comment]
Please check #170

**Comment by NiTROACTiVE** [comment]
> Please check #170

I found out which extension was causing the issue. Thanks for the help.
