### ISSUE TITLE
Download button not showing up

### ISSUE THREAD

**Issue by willag42** [EltonChou/TwitterMediaHarvest#2]
Hello.

For the past few weeks the download button has not been showing up on twitter posts with images or videos. I am uncertain if this started occurring around the same time as the 1.3.0 update, because I didn't track when I stopped seeing it.

I recently removed the extension from Chrome and then added it again to see if that would fix it, and it didn't.

I think I have the latest version of Chrome (Version 87.0.4280.66 (Official Build) (64-bit)).

Thanks.

**Comment by EltonChou** [comment]
Hi @willag42 .
Thanks for your feedback.

Please try the beta version [v1.3.1-beta](https://github.com/EltonChou/TwitterMediaHarvest/releases/download/v1.3.1-beta/media_harvest.zip).
This extension is relied on official layout of twitter.
If you are using other extension about twitter might make this extension unworkable.

Currently this extension can't track any issue from remote, 
it will be helpful if you are willing to report the issue you have.
---
[How to install Chrome unpacked extension](https://webkul.com/blog/how-to-install-the-unpacked-extension-in-chrome/)

**Comment by willag42** [comment]
Hello @EltonChou,

Thank you for the fix. The beta version v1.3.1-beta fixed the issue! I was able to download photos just a minute ago.

Where do you want me to report the issue?

Thanks.

**Comment by EltonChou** [comment]
@willag42 
Just feel free to open an issue in this repository.
Also, feature request is welcome 😃
