### ISSUE TITLE
[BUG] Filename pattern + .jpg_orig

### ISSUE THREAD

**Issue by hunii15** [EltonChou/TwitterMediaHarvest#204]
Hi. 

Just deleted and re-instealled to see if it was an error but not solved. 

When I download the image or video, the name saves as a random words (not as I set. Please see the screenshot I added).
And the extention is strange... '.jpg_orig' 
<img width="287" alt="스크린샷 2024-11-24 141459" src="https://github.com/user-attachments/assets/42df218f-becf-47aa-acaf-a7e54716d5c7">

How do I fix this?

**Screenshots**
![스크린샷 2024-11-24 140928](https://github.com/user-attachments/assets/a722ebc2-ed70-4109-9e06-a46a3091b881)

**Desktop (please complete the following information):**
 [Windows 11 Pro]
[Chrome]
 [131.0.6778.86]

**Additional context**

**Comment by EltonChou** [comment]
Please check #170.
