### ISSUE TITLE
Download directory won't accept blank

### ISSUE THREAD

**Issue by redpizza** [EltonChou/TwitterMediaHarvest#4]
but I don't want to download images to subdirectory.

**Comment by EltonChou** [comment]
Hi @redpizza 

Thanks for your report.
I will add an advanced option for directory control in next version.
If you have more suggestions, feel free to share with me.

**Comment by EltonChou** [comment]
Solved in [v1.4.0](https://github.com/EltonChou/TwitterMediaHarvest/releases/tag/v1.4.0).
