### ISSUE TITLE
Firefox version?

### ISSUE THREAD

**Issue by bremaya** [EltonChou/TwitterMediaHarvest#44]
Could you make a version available for the Firefox browser?  Thanks for the excellent extension!

**Comment by EltonChou** [comment]
> Could you make a version available for the Firefox browser? Thanks for the excellent extension!

Yes, I will make it works on firefox in next major version.

**Comment by EltonChou** [comment]
Here is the preview version for firefox.
It was still under test and it can perform the basic usages but may occur some bugs.

https://addons.mozilla.org/zh-TW/firefox/addon/media-harvest/
