### ISSUE TITLE
Typing "d" in a reply to a tweet

### ISSUE THREAD

**Issue by Enakin17** [EltonChou/TwitterMediaHarvest#58]
If you open a tweet from an image so that the URL becomes /photo/1 (e.g. https://twitter.com/JakeChams/status/1576615422987685888/photo/1) and then begin typing a reply that contains the letter "d", the extension downloads the media because of the shortcut. This doesn't seem to be the case when opening the tweet normally (without the /photo/1). 
![image](https://user-images.githubusercontent.com/34503844/230839314-33e8e76e-260d-4343-95d7-552524af7cdc.png)

**Comment by EltonChou** [comment]
> If you open a tweet from an image so that the URL becomes /photo/1 (e.g. https://twitter.com/JakeChams/status/1576615422987685888/photo/1) and then begin typing a reply that contains the letter "d", the extension downloads the media because of the shortcut. This doesn't seem to be the case when opening the tweet normally (without the /photo/1). ![image](https://user-images.githubusercontent.com/34503844/230839314-33e8e76e-260d-4343-95d7-552524af7cdc.png)

Thanks for your report. 👍 

I will add a filter to handle this issues.

**Comment by EltonChou** [comment]
Fixed in b2cb682.
