### ISSUE TITLE
[Feature] Downloading without confirmation  

### ISSUE THREAD

**Issue by nlboom** [EltonChou/TwitterMediaHarvest#65]
I would like to see a function about download to a specified folder without a confirmation screen.
I don't know if this is a bug, or if it was originally intended that way, but in version 3.2.8 for Firefox, that's media was downloading like this, but since version 4.0.0 it started asking for a save path.
For Twitter, I'm more comfortable with the first option, and I think this feature would be useful.

**Comment by EltonChou** [comment]
Hi @nlboom 

Thanks for your feedback.
You can control this settings in browser settings (`about:preferences#general`).

Firefox has some different behavior from the chromium-based browser.
I will set out how to control them well.

**Comment by EltonChou** [comment]
@nlboom 
The new version has been published in firefox addons store.
Please check if the new options is working in your environment.
