### ISSUE TITLE
[FEATURE] the ability to save gifs as .gif rather than .mp4

### ISSUE THREAD

**Issue by parappatherappr** [EltonChou/TwitterMediaHarvest#69]
**Is your feature request related to a problem? Please describe.**
i like saving gifs a lot, but theyre always downloaded as .mp4 instead of .gif

**Describe the solution you'd like**
it'd be awesome if i (and im sure many other people) could download them without having to convert them from the .mp4 file theyre saved as to .gif

**Comment by EltonChou** [comment]
Thanks for your feedback.

I would prefer gif format too. But the most of videos you saw on twitter were stored as `mp4` format.
Although the UI said the video is GIF format, twitter always convert them to MP4 on server. 
And I don't think converting the file back to GIF is a efficent way in a extension.
