### ISSUE TITLE
[BUG] Save image as dialog box delayed when extension is enabled

### ISSUE THREAD

**Issue by BitRYNO** [EltonChou/TwitterMediaHarvest#70]
**Describe the bug**
Right clicking on any image from any website and choosing 'save image as...' causes a long delay, about 5-8 seconds, before the save as box appears.  Disabling the extension stops the delay. 

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Browser Chrome 114.0.5735.110 (Official Build) (64-bit)
 - Version 4.1.0

**Comment by EltonChou** [comment]
Can you try to enable `Aggressive mode` in options page (Options > Integrations)
and let me know the result?

**Comment by BitRYNO** [comment]
Aggressive Mode fixed the behavior

**Comment by EltonChou** [comment]
Cool.
Can you try one more step for me?
oes the behavior occure again, if you disable the aggressive mode?

Aggressive mode has some side-effects in some scenarios.
If the bug could be solved, I recommend you turn-off the aggressive mode.

**Comment by EltonChou** [comment]
No further response.
