### ISSUE TITLE
[NOTIFICATION] Twitter API rate limit issue.

### ISSUE THREAD

**Issue by EltonChou** [EltonChou/TwitterMediaHarvest#73]
If you found the download failed. (the icon became red)
Please go to the options page of this extension and open DevTools (F12).
Run the script below in console.  (Only work on `>=v4.0.0`)

## UPDATE
+ In `>=v4.1.6`, the extension will try to save your quota of tweet view if you use `v1`

## Chrome, Edge or any Chromium based browser
```js
await chrome.storage.local.set({twitterApiVersion: 'gql'})
```
**This method shares the same rate limit with current API restriction.**

You can also try another script, but it not works on some tweets.
```js
await chrome.storage.local.set({twitterApiVersion: 'v1'})
```

## Firefox
```js
await browser.storage.local.set({twitterApiVersion: 'gql'})
```
or
```js
await browser.storage.local.set({twitterApiVersion: 'v1'})
```

**Comment by DealsBeam** [comment]
Thank you for your hard work

**Comment by outlaw420** [comment]
neither options for firefox seem to work for me, I just get 'undefined' in the dev console

**Comment by EltonChou** [comment]
> neither options for firefox seem to work for me, I just get 'undefined' in the dev console

@outlaw420 
Because this command doesn't return anything, so the console show `undefined`.

Use this to check the version was setup correctly.
```js
await browser.storage.local.get("twitterApiVersion") 
```
screenshot:
![image](https://github.com/EltonChou/TwitterMediaHarvest/assets/12560310/0500acfc-57fa-4504-96e9-6692a1f4425d)

The api is share rate-limit with current API rate-limit, if you reach the limit it will not works.
It will be helpful If you can provide error message .

**Comment by outlaw420** [comment]
I get `Source map error: Error: NetworkError when attempting to fetch resource.`
Tried disabling all addons besides TMH, and re-logging in 2 accounts that aren't rate-limited.
I tried it on a fresh firefox 115 install and it worked. I'm not sure what's wrong with my current ff profile. Weird.

**Comment by EltonChou** [comment]
> I get `Source map error: Error: NetworkError when attempting to fetch resource.` Tried disabling all addons besides TMH, and re-logging in 2 accounts that aren't rate-limited. I tried it on a fresh firefox 115 install and it worked. I'm not sure what's wrong with my current ff profile. Weird.

This warning shouldn't affect the operation.
Did you try reinstalling the add-on in you current profile ?
In some situation, you need to refresh the twitter page.

**Comment by outlaw420** [comment]
Running the script then reinstalling the addon worked. Thanks a lot!

**Comment by EltonChou** [comment]
@borez 
Can you provide the full error message screenshot?

**Comment by EltonChou** [comment]
@borez 
Source map error shouldn't affect the process.
It looks like that twitter api would be failed in your environment.

Please follow the instruction to go to the devtools page.

1. Go to extension management page.
2. Click the settings then choose Debug Add-ons.
3. Inspect Media Harvest
4. Switch to `Network` panel.
5. Click download button on tweet.

When you click download button it will record some info in `Network` panel.
Let me know the status code (in screenshot, it was 200 in green).

**Don't take screenshot for whole panel it might contains some security information. I only need status code and body**

![instruction](https://github.com/EltonChou/TwitterMediaHarvest/assets/12560310/f9e8d170-02b6-42f4-a18e-c36e3444ed73)

**Comment by borez** [comment]
@EltonChou thanks for the speedy reply. Unfortunately for some reason my extension decided to work, so won't be able to debug. Hopefully the next person with errors can assist!

Many thanks for your hard work.

**Comment by EltonChou** [comment]
Introduced adaptive api using in `v4.1.6`.
