### ISSUE TITLE
[BUG] Naming conflict with extension RegExp Download Organizer

### ISSUE THREAD

**Issue by PennHui666** [EltonChou/TwitterMediaHarvest#75]
**Describe the bug**

The download behavior of this extension has a naming conflict with another extension called _RegExp Download Organizer_.

**To Reproduce**

When the two extensions are used together, the suffix of the downloaded image will be named **jpg_orig**. 
The troublesome point is that the path where I store the file is the default ‘download address/website/twitter’. This download path is supported by _RegExp Download Organizer_ but _TwitterMediaHarvest_ not support. 
Also, once I enable the Aggressive Mode _RegExp Download Organizer_, it will fail. So I am now in a dilemma.

**Expected behavior**

I suggest that the developers can allow files to be saved in a deeper path, or try to fix this naming conflict.

**Desktop (please complete the following information):**
 - OS: Windows10
 - Browser: Edge
 - Version: 114.0.1823.51

**Additional context**

Just a matter of file naming and saving, not really a big deal. Developers please handle as appropriate.

**Comment by EltonChou** [comment]
Thanks for your feedback.
The filename problem is known issue on chromium bases browser.
When you use download management extension more than one it will cause filename race condition.

Ref: https://developer.chrome.com/docs/extensions/reference/downloads/#event-onDeterminingFilename
