### ISSUE TITLE
[BUG] Firefox does not work

### ISSUE THREAD

**Issue by kidzgy** [EltonChou/TwitterMediaHarvest#76]
**Describe the bug**
version4.1.3.
When the download button is clicked, the button turns red and no download window pops up.

**Screenshots**
![微信截图_20230704190656](https://github.com/EltonChou/TwitterMediaHarvest/assets/6967810/c526f610-10b9-43e4-8d42-828d665c92c5)
![微信截图_20230704191220](https://github.com/EltonChou/TwitterMediaHarvest/assets/6967810/6b411892-3e36-45eb-8ee7-ff81fdb0e3ab)

**Desktop (please complete the following information):**
 - OS: [e.g. iOS] Windows10 x64
 - Browser [e.g. chrome, safari] Firefox
 - Version [e.g. 22] 114

**Additional context**

**Comment by EltonChou** [comment]
CSP issues would be fixed today.

**Comment by kidzgy** [comment]
Thank You. It works.

**Comment by EltonChou** [comment]
Fixed in ea5bd3d380aa712c55b273723e4cdbc6ce06fb60
