### ISSUE TITLE
[FEATURE] Need Legacy tweetdeck support

### ISSUE THREAD

**Issue by oilpooh** [EltonChou/TwitterMediaHarvest#81]
Legacy tweetdeck  is back

**Comment by EltonChou** [comment]
I will publish v4.1.7 to restore legacy support afternoon.

**Comment by EltonChou** [comment]
Revived in [18b38f9](https://github.com/EltonChou/TwitterMediaHarvest/commit/18b38f9a5a163211fb2892558df6839a39550225).
