### ISSUE TITLE
[FEATURE] Output a direct video link instead of downloading it

### ISSUE THREAD

**Issue by ara303** [EltonChou/TwitterMediaHarvest#86]
**Is your feature request related to a problem? Please describe.**
Sometimes all I really want is to extract a video link but I don't want to download it. Previously extensions existed that would open a new tab with a direct URL to the video on Twitter's server - usually `video.twimg.com` - which I personally found surprisingly useful for a quick, easy share of a video. If I have to download that adds a layer of friction (have to work out where it saved to, find it, re-upload it in Discord/Slack/etc.) when I could just drop the direct video URL in a message previously.

**Describe the solution you'd like**
I propose an option could be added to TwitterMediaHarvest to output the video URL instead of downloading it locally. It should not be the default, but would be an excellently useful option. Either it could copy the video's direct URL to clipboard or just open it in a new tab so I can copy that URL from there.

**Describe alternatives you've considered**
The exact feature I describe here was previously supported by [twMediaDownloader](https://github.com/furyutei/twMediaDownloader), which had the ability to just open a direct video URL in a new tab instead of downloading it, but this broke when Twitter turned off the guest API key that extension used (I think? I'm not sure). 

**Additional context**
So far as I can tell this could be a useful and unique feature to TMH if it were added. In my hunt for an extension that offers this functionality I've so far found nothing. _All_ Twitter video downloaders only offer the ability to download, none offer the ability to just extract the link.

I'd be happy to donate to the extension if this got added. I sincerely miss it from twMediaDownloader!

**Comment by EltonChou** [comment]
Interesting concept.
Why don't you just share the link of tweet to other people?

**Comment by ara303** [comment]
It's about consistency. Before, with how this feature worked in twMediaDownloader, I could send the direct video URL and know it'd embed in whatever chat I was using. I also noticed some accounts on Twitter sometimes run afoul of the automatic (and flawed) adult content detection and linking to those tweets didn't embed correctly in Discord, for example. Having a direct video URL worked no matter where I wanted to send it. This became all the more useful when logged-out users couldn't access any content and/or sending links to people who refused to make Twitter accounts on protest grounds, etc. 

I admit it's a niche use case but I personally found it very useful in twMediaDownloader and am disappointed it's broken in that extension!

**Comment by EltonChou** [comment]
Some services like [vxtwitter](https://github.com/dylanpdx/BetterTwitFix) has provided better sharing experience in chatroom app and if you really need the source url of media you can get it in download history currently.

The main usage of this extension is still a downloader, this feature might be implemented someday but it would be lower priority in current roadmap.
