### ISSUE TITLE
[BUG] Tweets with 2+ vids or mixed media only download first file

### ISSUE THREAD

**Issue by anonbergine** [EltonChou/TwitterMediaHarvest#87]
**Describe the bug**

If a tweet contains 2 vids, or different kinds of media (eg. photo and vids), only the first media item is downloaded.

**To Reproduce**

1. Example tweet with 2 vids: https://twitter.com/taliaotg/status/1679987354579136513
2. Click the download button, only the first vid is downloaded

**Expected behavior**

Both vids should download, eg. I should have 2 files:

1. taliaotg-1679987354579136513-01.mp4
2. taliaotg-1679987354579136513-02.mp4

**Desktop (please complete the following information):**

 - OS: Win 10
 - Browser: Firefox
 - Version: 115.0.2 (64-bit)

**Comment by EltonChou** [comment]
Twitter changed API, I will fix it asap.

**Comment by EltonChou** [comment]
Is it work properly now?
It looks like it was cache issue.
Some api endpoints didn't reflect the latest content.
