### ISSUE TITLE
[FEATURE] Choose resolution (primarily for vid downloads)

### ISSUE THREAD

**Issue by anonbergine** [EltonChou/TwitterMediaHarvest#88]
**Is your feature request related to a problem? Please describe.**

Currently it seems to always download the highest resolution of a video.

**Describe the solution you'd like**

I archive twitter threads on certain themes, and media download is a key component of that. So is file size mangement.

If I understand correctly, twitter has three versions of a vid to choose from - small, medium, large.

I'd like to set default choice in settings, eg. default to the medium video size.

But also to be able to override for any specific tweet download - eg. right-click the download button to show a menu listing the resolutions, then click the desired resolution to download it.

**Describe alternatives you've considered**

Currently I have to use external website which is extremely time consuming when archiving threads.

Eg. On this site you enter tweet URL, then on next page it shows the three resolutions to choose from (it also handles tweets with multiple vids, etc): https://www.twitsave.com/

![image](https://github.com/EltonChou/TwitterMediaHarvest/assets/120770250/eebf80ef-5b87-4eb9-bd35-36d4138454bd)

**Comment by EltonChou** [comment]
Thanks for your feedbacks.

This feature will violate the core concept and break the framework of this extension.
If you need to achieve the whole thread on certain theme, you should find other tools support batch-download.

Core concept:
1. One-click
2. Original size
