### ISSUE TITLE
[FEATURE] Archive thread

### ISSUE THREAD

**Issue by anonbergine** [EltonChou/TwitterMediaHarvest#89]
**Is your feature request related to a problem? Please describe.**

I archive threads for research. Currently a manual process:

1. Create text file (eg. `{op_tweet_id}.txt`)
2. Copy paste over the tweet URLs and their text
3. Also download media for each tweet
4. Save text file upon reaching end of thread

**Describe the solution you'd like**

1. Right-click download button in a thread (see also: #88)
2. Choose "Archive" from pop-up menu
3. All tweets in thread from that author are compiled in to a text file, and the media from those tweets is also downloaded

Example text file:

```
https://twitter.com/{user_id}/status/{tweet_id}

{tweet_text}

https://twitter.com/{user_id}/status/{tweet_id}

{tweet_text}

...
```

If it could continue archiving past the "show more" boundary that would be ideal.

**Describe alternatives you've considered**

I've tried web archive (both wayback machine and archive.today) but they are not good with videos. They also tend to archive a bunch of stuff I'm not interested in such as replies, ads, etc.

I've tried save as PDF which kinda works but is cumbersome to use (eg. large file size and embedded media is a PITA to work with)

Hence I just do it manually. Text file is nice and small, and easily searchable, and having vids/images as sepaerate files makes them easy to work with.

**Additional context**

Ability to customise media resolution (small, medium, large) in settings - see #88 

Also, maybe change border of archived tweets so I can visually see what's been saved to disk. Sometimes threads break or author will reply 2+ times to a tweet in the thread which can cause confusion - so I'd need to go in and manually deal with that.

**Comment by EltonChou** [comment]
This extension is not a batch-downloader or backup tool.
