### ISSUE TITLE
[BUG] Downloads failing in Firefox 116.0.1

### ISSUE THREAD

**Issue by grxnola** [EltonChou/TwitterMediaHarvest#94]
**Describe the bug**
Videos fail to download, with a red download icon.

**To Reproduce**
1. Navigate to video
2. Click download

**Expected behavior**
A video would be downloaded and saved in the twitter_media_harvest directory.

**Desktop (please complete the following information):**
 - OS: NixOS 23.05
 - Browser: Firefox
 - Version: 116.0.1 (64-bit)

**Additional context**
This is output in the Firefox Javascript console:
```
Source map error: Error: NetworkError when attempting to fetch resource.
Resource URL: moz-extension://75cacb31-1741-450f-9981-82ca9662b397/main.js
Source Map URL: main.js.map
```

**Comment by EltonChou** [comment]
Can you provide the link to the tweet?
Did this issue only occur once or many times?

**Comment by EltonChou** [comment]
No furthereresponse. Can't reproduce error.
