### ISSUE TITLE
[BUG] Settings was reset after update.

### ISSUE THREAD

**Issue by fireattack** [EltonChou/TwitterMediaHarvest#98]
**Is your feature request related to a problem? Please describe.**
Just noticed that after updating to 4.2.0, the settings for Filename Pattern got reset.

I have to re-download all the files I downloaded afterwards since the default filenames don't have the information I needed. 

**Describe the solution you'd like**

It's not a big deal, but in future I wish update doesn't reset user's settings.

**Comment by EltonChou** [comment]
This update did not reset any settings.
Under investigation but I haven't observed same behavior.

**Comment by fireattack** [comment]
Then I guess it's just an one-off thing that happens due to unknown reasons. I will close the issue unless it happens again or I have any clue what causes it. 

Thanks for investigating it!
